- name: 'Deploy gcp vm'
  hosts: localhost
  connection: local
#  ansible_ssh_private_key_file: "/home/ansible/.ssh/id_rsa"
  become: false
  gather_facts: no
  vars:
    gcp_project: "79517034944"
    gcp_cred_kind: "serviceaccount"
    gcp_cred_file: "linux-devops-3000-b420b44fd512.json"
    gcp_region: "us-central1"
    gcp_zone: "us-central1-a"
    disk_size: 30
    image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts"
    envi: "staging"


  # Roles & Tasks
  tasks:
    - name: create a disk for instance 1
      gcp_compute_disk:
        name: instance1
        size_gb: "{{ disk_size }}"
        source_image: "{{ image }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk1

    - name: create a address for instance 1
      gcp_compute_address:
        name: 'instance1'
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address1

    - name: create instance 1
      gcp_compute_instance:
        name: instance1
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        machine_type: n1-standard-1
        disks:
          - auto_delete: 'true'
            boot: 'true'
            source: "{{ disk1 }}"
        labels:
          environment: "{{ envi }}"
        network_interfaces:
          - network: null
            access_configs:
              - name: External NAT
                nat_ip: "{{ address1 }}"
                type: ONE_TO_ONE_NAT
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: instance

###########################################
    - name: create a disk for instance 2
      gcp_compute_disk:
        name: instance2
        size_gb: "{{ disk_size }}"
        source_image: "{{ image }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk2

    - name: create a address for instance 2
      gcp_compute_address:
        name: 'instance2'
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address2

    - name: create instance 2
      gcp_compute_instance:
        name: instance2
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        machine_type: n1-standard-1
        disks:
          - auto_delete: 'true'
            boot: 'true'
            source: "{{ disk2 }}"
        labels:
          environment: "{{ envi }}"
        network_interfaces:
          - network: null
            access_configs:
              - name: External NAT
                nat_ip: "{{ address2 }}"
                type: ONE_TO_ONE_NAT
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: instance


